### ISSUE TITLE
Mega link broken 

### ISSUE THREAD

**Issue by radha1990kumari** [baquer/GATE-and-CSE-Resources-for-Students#14]
For Made Easy Theory Notes and Practice Booklet : https://mega.nz/folder/knQEWbxB#_nLz5TMN1zoYWIfEY9whDw

**Comment by baquer** [comment]
> For Made Easy Theory Notes and Practice Booklet: https://mega.nz/folder/knQEWbxB#_nLz5TMN1zoYWIfEY9whDw

Will add a new mega link for bookets.
